version: '3'

networks:
  web:
    external: true

services:
  job:
    build: .
    container_name: job
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi; python3 manage.py bot'
    volumes:
      - .:/home/user/web
    restart: always
    ports:
      - '8080:8000'
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.job.rule=Host(`$DOMAINNAME`)"
      #- "traefik.http.routers.job.tls=true"
      ## HTTP Routers
      - "traefik.http.routers.job-rtr.entrypoints=https"
      - "traefik.http.routers.job-rtr.rule=Host(`$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.job-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.job-rtr.service=django-svc"
      - "traefik.http.services.job-svc.loadbalancer.server.port=8000"
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - web