version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  job:
    build: .
    container_name: job
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi;'
    volumes:
      - .:/home/user/web
    restart: always
    ports:
      - '8089:8000'
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.job-rtr.entrypoints=https"
      - "traefik.http.routers.job-rtr.rule=Host(`$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.job-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.job-rtr.service=job-svc"
      - "traefik.http.services.job-svc.loadbalancer.server.port=8000"
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - web
      - internal

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python3 manage.py bot'
    volumes:
      - .:/home/user/web
    restart: always
    networks:
      - web
      - internal

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - web
      - internal

  worker:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/user/web
    command: bash -c 'celery -A config worker --loglevel=info'
    networks:
      - web
      - internal

  celery-beats:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/user/web
    command: bash -c 'celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    networks:
      - web
      - internal